% 20191123 by Dushan N. Wadduwage (wadduwage@fas.harvard.edu)
% 20200429 modified by Dushan N. Wadduwage (wadduwage@fas.harvard.edu)
% segmenter

function net = tr_segmenter(net0,imds_gt,pxds_gt,pram)
    
    %% network parameters 
    patchSize       = [pram.Nx pram.Nx];
    miniBatchSize   = 64;
    numClasses      = pram.N_classes;
    classNames      = pram.classNames;
    pixelLabelIDs   = pram.pxLblIds;

    %% set other datastore parameters
    I_temp          = imds_gt.read;     
    imds_gt.reset;    
    N_PatchesPerImg = prod(size(I_temp)./patchSize)*16;
    
    %% image-patch datastores
    patchds_tr                  = randomPatchExtractionDatastore(imds_gt,pxds_gt,patchSize,'PatchesPerImage',N_PatchesPerImg);
    patchds_tr.MiniBatchSize    = miniBatchSize;
    lgraph = layerGraph(net0);    
        
    %% train network
    maxEpochs = 8;
    epochIntervals = 10;
    initLearningRate = 0.1;
    learningRateFactor = 0.1;
    l2reg = 0.0001;
    options = trainingOptions('sgdm', ...
        'Momentum',0.9, ...
        'InitialLearnRate',initLearningRate, ...
        'LearnRateSchedule','piecewise', ...
        'LearnRateDropPeriod',max(maxEpochs/4,1), ...
        'LearnRateDropFactor',learningRateFactor, ...
        'L2Regularization',l2reg, ...
        'MaxEpochs',maxEpochs ,...        
        'ValidationFrequency', 500, ...
        'MiniBatchSize',miniBatchSize, ...
        'GradientThresholdMethod','l2norm', ...
        'Plots','training-progress', ...
        'GradientThreshold',0.01,...
        'ExecutionEnvironment','multi-gpu');                % 'ValidationData',patchds_val,...

    net = trainNetwork(patchds_tr,lgraph,options);
    save(['./_trainedNetworks/'...
           pram.net_nameStem ...
           sprintf('_%dx%d_%s.mat',patchSize(1),patchSize(2),date)],...
           'net');

end